(() => {
  const form=document.querySelector('#upload-form'), input=document.querySelector('#files'), gallery=document.querySelector('#gallery'), status=document.querySelector('#status'), dialog=document.querySelector('#preview');
  const category=document.querySelector('#category'), group=document.querySelector('#photo-group');
  function updateGroup(){const photo=category.value==='photography';document.querySelector('#photo-group-field').hidden=!photo;group.disabled=!photo;}
  category.addEventListener('change',updateGroup);updateGroup();
  let items=[], filter='all', previews=[], opener;
  const labels={photography:'Photography',art:'Art & making',table:'At the table'};
  function message(text,error=false){status.textContent=text;status.classList.toggle('error',error);}
  async function api(url,options){const response=await fetch(url,options);let result;try{result=await response.json();}catch{throw Error('The local studio server is not responding. Start server.py and open the studio from localhost.');}if(!response.ok)throw Error(result.error||'Something went wrong. Please try again.');return result;}
  function element(tag,className,text){const node=document.createElement(tag);if(className)node.className=className;if(text!==undefined)node.textContent=text;return node;}
  function render(){gallery.replaceChildren();document.querySelector('#count').textContent=`${items.length} ${items.length===1?'piece':'pieces'}`;const visible=items.filter(item=>filter==='all'||item.category===filter);if(!visible.length){const empty=element('div','empty');empty.append(element('strong','',items.length?'A little space to fill.':'Your collection starts here.'),element('p','',items.length?'Add a piece to this collection, or explore another category.':'Choose a photograph, a painting, or a moment around the table.'));gallery.append(empty);return;}visible.forEach(item=>{const article=element('article','piece'),view=element('button','piece-view'),img=element('img');view.type='button';view.setAttribute('aria-label',`Preview ${item.title}`);img.src=item.url;img.alt=item.title;img.loading='lazy';view.append(img);view.addEventListener('click',()=>{opener=view;document.querySelector('#preview-image').src=item.url;document.querySelector('#preview-image').alt=item.title;document.querySelector('#preview-title').textContent=item.title;document.querySelector('#preview-caption').textContent=item.caption;dialog.showModal();});const meta=element('div','piece-meta'),title=element('div');title.append(element('h3','',item.title),element('span','piece-category',labels[item.category]||item.category));const remove=element('button','remove','Remove');remove.type='button';remove.setAttribute('aria-label',`Remove ${item.title}`);remove.addEventListener('click',async()=>{if(!confirm(`Remove “${item.title}” from your local collection? This deletes the uploaded copy.`))return;remove.disabled=true;try{await api(`/api/gallery/${item.id}`,{method:'DELETE'});items=items.filter(entry=>entry.id!==item.id);render();message('Piece removed from your collection.');}catch(error){message(error.message,true);remove.disabled=false;}});meta.append(title,remove);article.append(view,meta);if(item.caption)article.append(element('p','piece-caption',item.caption));gallery.append(article);});}
  function selected(){previews.forEach(url=>URL.revokeObjectURL(url));previews=[];const container=document.querySelector('#selected');container.replaceChildren();const files=[...input.files];files.slice(0,10).forEach(file=>{if(!['image/jpeg','image/png','image/webp'].includes(file.type))return;const url=URL.createObjectURL(file);previews.push(url);const img=element('img');img.src=url;img.alt=file.name;container.append(img);});if(files.length)container.append(element('span','',`${files.length} ${files.length===1?'image':'images'} selected`));}
  input.addEventListener('change',selected);const drop=document.querySelector('#drop-zone');['dragenter','dragover'].forEach(name=>drop.addEventListener(name,event=>{event.preventDefault();drop.classList.add('dragover');}));['dragleave','drop'].forEach(name=>drop.addEventListener(name,()=>drop.classList.remove('dragover')));drop.addEventListener('drop',event=>{event.preventDefault();if(event.dataTransfer.files.length){input.files=event.dataTransfer.files;selected();}});
  form.addEventListener('submit',async event=>{event.preventDefault();const files=[...input.files];if(!files.length)return message('Choose at least one image.',true);if(files.length>10)return message('Choose up to 10 images at once.',true);if(files.some(file=>file.size>12*1024*1024))return message('Each image must be at most 12 MB.',true);const button=form.querySelector('[type=submit]');button.disabled=true;button.textContent='Adding to your collection…';message('Saving your images on this computer…');try{const result=await api('/api/gallery',{method:'POST',body:new FormData(form)});items=[...result.items,...items];form.reset();updateGroup();selected();filter='all';document.querySelectorAll('[data-filter]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.filter==='all')));render();message(`${result.items.length===1?'Your piece has':'Your pieces have'} been added. Open the portfolio to see the collection.`);}catch(error){message(error.message,true);}finally{button.disabled=false;button.textContent='Add to collection';}});
  document.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>{filter=button.dataset.filter;document.querySelectorAll('[data-filter]').forEach(other=>other.setAttribute('aria-pressed',String(other===button)));render();}));
  document.querySelector('#preview-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>opener?.focus());dialog.addEventListener('click',event=>{const r=dialog.getBoundingClientRect();if(event.target===dialog&&(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom))dialog.close();});
  api('/api/gallery').then(result=>{items=result.items;render();}).catch(error=>{message(error.message,true);gallery.append(element('p','empty','Start the local server to manage your collection.'));});
})();
